version: "3"

services:
  nodejs:
    image: ${NODEJS_IMG}
    build:
      context: ./node
    container_name: nodejs_server
    hostname: nodejsserver
    ports:
      - "3000:3000"
    networks:
      - mern-net
    volumes:
      - ./uploads:/usr/src/node_app/public
    env_file:
      - .env

  nextjs:
    image: ${NEXTJS_IMG}
    build:
      context: ./next
    container_name: nextjs
    hostname: nextjs
    ports:
      - "4000:4000"
    depends_on:
      - nodejs
    networks:
      - mern-net
    env_file:
      - .env

  nginx:
    image: ${NGINX_IMG}
    build:
      context: ./nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
    depends_on:
      - nodejs
    networks:
      - mern-net
    env_file:
      - .env

networks:
  mern-net:
    external: true
