FROM node:18.16.0
WORKDIR /usr/src/nextjs_app
COPY ./package*.json /usr/src/nextjs_app/
RUN npm install
COPY ./ /usr/src/nextjs_app/
RUN npm run build
RUN npm install pm2 -g
EXPOSE 4000
CMD ["pm2-runtime", "npm", "--", "run", "start", "--", "-p", "4000"]